source 'https://rubygems.org'


gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'simple_form', '~> 3.0.2'
gem 'devise', '~> 3.4.0'
gem 'paperclip', '~> 4.2.0'
gem 'masonry-rails', '~> 0.2.1'
gem 'acts_as_votable', '~> 0.10.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development
