# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e343aaf05ac135a96919b84d48dc9330cbd9b4b2d3400a59b747fe7f202489037c2395e480c91dfa2a7aee7a78d8a38e126b705f28af833912b5ea0ba86fb9

test:
  secret_key_base: 6ac24d35d3d69fdcc67b01356be0f3ffb567f9a2568d4e5b557059defe87ab2240f27ef604b13f5500f8a37b5e4275d76a3b0612aa9c3019c6b2e693f3818735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
